version: '2'
services:
    hipstagram-app:
        image: hipstagram
        external_links:
            - hipstagram-postgresql:postgresql
            - hipstagram-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/hipstagram
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    hipstagram-postgresql:
        extends:
            file: postgresql.yml
            service: hipstagram-postgresql
    hipstagram-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hipstagram-elasticsearch
